### ISSUE TITLE
Canvas error

### ISSUE THREAD

**Issue by Shashikiran200212** [adrianhajdin/figma_clone#6]
It is showing no errors in console and everything seems fine in the code , but when i am clicking on the canvas the shapes are not appearing. PLZ HELP 
in your video the process starts from 1:56:30 
i guess from there is some error in my code

**Comment by 0x86e3x4** [comment]
I also had the same issue check issue #3 and maybe it might solve the issue

**Comment by Shashikiran200212** [comment]
no matter i change anything the canvas is not working

**Comment by Shashikiran200212** [comment]
i guess it has something to do with fabric.
PLZ CHECK INTO IT

**Comment by Labedlam** [comment]
I'm having the same issue. I updated the next.config.mjs to the one suggested on issue https://github.com/adrianhajdin/figma_clone/issues/3,  But it seems like mouse down listener is not being triggered.
